### ISSUE TITLE
How to execute ssd_pascal_video or webcam?

### ISSUE THREAD

**Issue by mintlatte** [dtmoodie/caffe#10]
I've got pre-built Caffe.
So, I copied examples/ssd folder into pre-build Caffe examples folder.
After that, I run cmd, move to Caffe folder and typed "python examples/ssd/ssd_pascal_video.py"
But this error showed up
//
C:\Python27\lib\site-packages\caffe\pycaffe.py:13: RuntimeWarning: to-Python con
verter for class boost::shared_ptr<class caffe::Net<float> > already registered;
 second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
C:\Python27\lib\site-packages\caffe\pycaffe.py:13: RuntimeWarning: to-Python con
verter for class boost::shared_ptr<class caffe::Blob<float> > already registered
; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
C:\Python27\lib\site-packages\caffe\pycaffe.py:13: RuntimeWarning: to-Python con
verter for class boost::shared_ptr<class caffe::Solver<float> > already register
ed; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
Traceback (most recent call last):
  File "examples/ssd/ssd_pascal_video.py", line 3, in <module>
    from caffe.model_libs import *
ImportError: No module named model_libs
//

I don't understand this error.
Is any other method to run ssd?
Could you tell me how to that?

Thank you!

**Comment by dtmoodie** [comment]
Hello,
You're missing: https://github.com/dtmoodie/caffe/blob/test_ssd_merge/python/caffe/model_libs.py
Which was likely just missed in the branch you are working off of.

**Comment by mintlatte** [comment]
@dtmoodie  Thank you! I will try that.
