### ISSUE TITLE
Some questions ....

### ISSUE THREAD

**Issue by MyVanitar** [dtmoodie/caffe#7]
Hello,

1) Should this repository be compiled or it is ready?

2) Can I use it with VS2015, Cuda 8.0 and CuDNN5.1?

3) Can the python files run if we define the Caffe path to this repository? Where PythonPath would be?

4) What is the best method to run` .ipynb `files under Windows?

You know it doesn't matter for me if I create IMDB files or train inside Linux for the models such as SSD, I want to make the final codes portable on Windows

**Comment by dtmoodie** [comment]
Hello,

This repo should be compiled.  I can provide binaries for msvc 2015 update 2 with CUDA 8.0 if you'd like.

2) Yes! http://dtmoodie.blogspot.com/2016/09/getting-caffe-running-on-windows-with.html -- While it hasn't been updated to the most recent patch of cuda which supports MSVC 2015 update 2+, these instructions go through getting caffe running on windows with python support with cuda 8.0 and cudnn 5.1.

3)  Yes, caffe with python works on windows and I've even tested it with jupyter-notebook.  I install caffe to G:/libs/caffe and then add G:/libs/caffe/python to my python path.

4)
````
import sys
sys.path.append('G:/libs/caffe/python')
import caffe
````

I've tested SSD models trained on Linux with my merge_nvidia branch (better multi gpu scaling) and deployed with my merge_branch on windows and it works.

Comment back if you have any problems.  Sorry for my late reply.

**Comment by MyVanitar** [comment]
Thank you very much.

1) Yes, I can make databases and train the SSD under Linux, which provides `deploy.prototxt` and `.caffemodel` basically. Then I want to bring these to the Windows and run the similar python or `.ipynb` files to detect objects (I don't remember exact file names). 
With your description, my assumption is practical and it will work in Windows, Yes?

2) if I copy-paste your compiled repo on a different computer (different in hardware but identical in configurations such as Cuda, python, CPU, GPU), does it work?

3) is there any way to run `.ipynb` files on Windows without using Jupyter notebook?

4) is there any method to install required python packages in Windows offline (assuming the target machine does not have access to the internet)?

5) I have an open issue somewhere else which will finally get connected to your repo to work. so I appreciate if you have any more information about these questions (here: https://github.com/sanghoon/pva-faster-rcnn/issues/63).

**Comment by dtmoodie** [comment]
1) Yes, I've done the same.

2) Yes it should work so long as you copy all dependent libraries and you have a cuda compatible driver installed on the deployment computer.  Make sure you compile caffe against enough different gpu architectures so that it covers the architecture of the deployment computer.  I suggest 3.0, 3.5, 5.0, 6.0.

3) I don't know, I've never used an ipynb outside of jupyter on windows or Linux.  You can try making a regular python script to do your inference.

4) Not sure, you can package your entire python directory and deploy it by unpacking though.

5) Are you asking the same questions in the link with respect to this repo?
- I convert my annotations to pascal format then use the original author's tools to create the lmdb file.
- I use the following command from a jupter notebook on Linux: 
````
convert_annoset_executable = caffe_root + '/build/tools/convert_annoset'
labelmap_file = 'labelmap_cityscapes_mini.prototxt'
output_lmdb = root + output + '/lmdb'
train_lmdb = output_lmdb + '/train'
test_lmdb = output_lmdb + '/test'
! $convert_annoset_executable --anno_type=detection --encode_type=png --label_map_file=$labelmap_file_abs $root $train_filelist $train_lmdb
````
- I'm not sure what you mean by modify cfg / prototxt.

**Comment by MyVanitar** [comment]
Thank you again. Thumb up.

1) Good that you have trained the PVANET+ either. Yes it is with the respect to your repo, because I want to run it on your repo and Windows after training. actually I had stuck in making the imdb file which should be **one** file based on this example (https://github.com/sanghoon/pva-faster-rcnn/tree/master/models/pvanet/example_train)

in the Pascal VOC format we have train and test which each file name has its own corresponding `.xml` file, such as `a.jpg` and `a.xml`, am I right? if Not, what is the format of annotations here and is there any tool to generate that? I think in your case the file which contains the annotations should be `labelmap_cityscapes_mini.prototxt`.
also, it seems the tool to convert the annotations to imdb will be generated after building the repo.

2) When we train the PVANET+, there is another file such as `yml`, I meant this, if it needs some modifications or not (here: https://github.com/sanghoon/pva-faster-rcnn/tree/master/models/pvanet/example_train).

**Comment by dtmoodie** [comment]
I'm sorry there may be some confusion.  I haven't done anything with PVANET.

You are correct that each image file should have a corresponding xml file.
The train and test set are then split into a train and test file list which contains the path to the image and the path to the xml file.  The train and test file list is then input into convert_annoset to create the lmdb files.  
Furthermore SSD requires a test name size file which contains a pairing of the image index the width and the height.  That file looks like this:
````
000000 1024 2048
000001 1024 2048
000002 1024 2048
000003 1024 2048
000004 1024 2048
````

The name size file is placed into the variable 'name_size_file' in this file:
https://github.com/dtmoodie/caffe/blob/merge/examples/ssd/ssd_pascal.py

**Comment by MyVanitar** [comment]
you are right about SSD. I gonna try it on your repo in next days. thank you for the support. 
if you could find any info about PVANET imdb creation part, please inform me. I stuck in that stage. it is a good model with higher mAP compared to SSD.
